# Generated by Django 5.0.6 on 2024-08-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsuranceApp', '0002_alter_customer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='claim_status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
