# Generated by Django 5.0.6 on 2024-08-09 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsuranceApp', '0004_remove_insurancepolicy_nominee_of_policy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='nominee',
        ),
        migrations.AddField(
            model_name='nominee',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nominees', to='InsuranceApp.customer'),
        ),
    ]
